### ISSUE TITLE
Produit scalaire avec tous les films en proposition

### ISSUE THREAD

**Issue by damien-peltier-cko** [clement-escolano/demande-moi-des-films#2]
Quand on commence le travail, on débute par comparer le vecteur de film likés (proposés par le chatbot) vs les utilisateurs du fichier ratings-popular-simplified. 

Problème, le chatbot va chercher les films dans toute la base de film qui est beaucoup plus grande que les films répertoriés dans le ratings-popular. Donc on tombe souvent sur 5 films qui ont 0 ratings dans rating-popular et donc le produit scalaire ne sert plus à rien.

Je propose que le chatbot ne propose que des films populaires au début.

**Comment by clement-escolano** [comment]
@Peltierdams Je suis bien d'accord. Par contre, je me souviens plus très bien comment j'avais généré le fichier `ratings-popular-simplified` mais en gros les fichiers "officiels" ce sont `movies.csv` et `ratings.csv`. Tout le reste je l'ai généré avec `utils.py` mais c'est pas certain que ce soit bien fait.
